apiVersion: v1
entries:
  ollama:
  - annotations:
      artifacthub.io/category: ai-machine-learning
      artifacthub.io/changes: |
        - kind: changed
          description: upgrade app version to 0.3.14
    apiVersion: v2
    appVersion: 0.3.14
    created: "2024-11-05T13:03:28.482093+01:00"
    description: Get up and running with large language models locally.
    digest: 2001ece9d5ccb9f9eeba72bfaa6c8aea8e33cdc83aa0d20f99c1cdd849c6915e
    home: https://ollama.ai/
    icon: https://ollama.ai/public/ollama.png
    keywords:
    - ai
    - llm
    - llama
    - mistral
    kubeVersion: ^1.16.0-0
    maintainers:
    - email: contact@otwld.com
      name: OTWLD
    name: ollama
    sources:
    - https://github.com/ollama/ollama
    - https://github.com/otwld/ollama-helm
    type: application
    urls:
    - https://mbtraore.github.io/cuddly-computing-machine/ollama-0.63.0.tgz
    version: 0.63.0
  - annotations:
      artifacthub.io/category: ai-machine-learning
      artifacthub.io/changes: |
        - kind: changed
          description: upgrade app version to 0.3.14
    apiVersion: v2
    appVersion: 0.3.14
    created: "2024-11-05T13:03:28.4856096+01:00"
    description: Get up and running with large language models locally.
    digest: 2001ece9d5ccb9f9eeba72bfaa6c8aea8e33cdc83aa0d20f99c1cdd849c6915e
    home: https://ollama.ai/
    icon: https://ollama.ai/public/ollama.png
    keywords:
    - ai
    - llm
    - llama
    - mistral
    kubeVersion: ^1.16.0-0
    maintainers:
    - email: contact@otwld.com
      name: OTWLD
    name: ollama
    sources:
    - https://github.com/ollama/ollama
    - https://github.com/otwld/ollama-helm
    type: application
    urls:
    - https://mbtraore.github.io/cuddly-computing-machine/charts/ollama-0.63.0.tgz
    version: 0.63.0
  open-webui:
  - annotations:
      licenses: MIT
    apiVersion: v2
    appVersion: 0.3.35
    created: "2024-11-05T13:03:28.4840601+01:00"
    dependencies:
    - condition: ollama.enabled
      import-values:
      - child: service
        parent: ollama.service
      name: ollama
      repository: https://otwld.github.io/ollama-helm/
      version: '>=0.24.0'
    - condition: pipelines.enabled
      import-values:
      - child: service
        parent: pipelines.service
      name: pipelines
      repository: https://helm.openwebui.com
      version: '>=0.0.1'
    description: "Open WebUI: A User-Friendly Web Interface for Chat Interactions
      \U0001F44B"
    digest: 17db1767378f247862803d0d2d5d0bbeb59368f9b643654ecc00b37ca1b2797c
    home: https://www.openwebui.com/
    icon: https://raw.githubusercontent.com/open-webui/open-webui/main/static/favicon.png
    keywords:
    - llm
    - chat
    - web-ui
    name: open-webui
    sources:
    - https://github.com/open-webui/helm-charts
    - https://github.com/open-webui/open-webui/pkgs/container/open-webui
    - https://github.com/otwld/ollama-helm/
    - https://hub.docker.com/r/ollama/ollama
    urls:
    - https://mbtraore.github.io/cuddly-computing-machine/open-webui-3.5.0.tgz
    version: 3.5.0
  pipelines:
  - annotations:
      licenses: MIT
    apiVersion: v2
    appVersion: alpha
    created: "2024-11-05T13:03:28.4845985+01:00"
    description: 'Pipelines: UI-Agnostic OpenAI API Plugin Framework'
    digest: ab13acb3869193ec3fcdea3c0ff59e5ef85d997322bd7b2444cdbfce998709cc
    home: https://github.com/open-webui/pipelines
    icon: https://github.com/open-webui/pipelines/raw/main/header.png
    keywords:
    - llm
    - chat
    - web-ui
    name: pipelines
    sources:
    - https://github.com/open-webui/helm-charts
    - https://github.com/open-webui/pipelines/pkgs/container/pipelines
    urls:
    - https://mbtraore.github.io/cuddly-computing-machine/pipelines-0.0.4.tgz
    version: 0.0.4
  - annotations:
      licenses: MIT
    apiVersion: v2
    appVersion: alpha
    created: "2024-11-05T13:03:28.4861354+01:00"
    description: 'Pipelines: UI-Agnostic OpenAI API Plugin Framework'
    digest: ab13acb3869193ec3fcdea3c0ff59e5ef85d997322bd7b2444cdbfce998709cc
    home: https://github.com/open-webui/pipelines
    icon: https://github.com/open-webui/pipelines/raw/main/header.png
    keywords:
    - llm
    - chat
    - web-ui
    name: pipelines
    sources:
    - https://github.com/open-webui/helm-charts
    - https://github.com/open-webui/pipelines/pkgs/container/pipelines
    urls:
    - https://mbtraore.github.io/cuddly-computing-machine/charts/pipelines-0.0.4.tgz
    version: 0.0.4
generated: "2024-11-05T13:03:28.4809916+01:00"
